---
title: Phat Ng Luu
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
markdown: kramdown
commonmark:
  options:
  - SMART
  - FOOTNOTES
  extensions:
  - strikethrough
  - autolink
  - table
  - tagfilter
exclude:
- Gemfile
- Gemfile.lock
