# After editing this configuration
# Run bundle exec jekyll serve
title: Phat Ng Luu
markdown: kramdown
commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]


# Exclude from processing
# The following items will not be processed:
exclude: [
  Gemfile,
  Gemfile.lock,
]
# Add variables here, it will access by {{ site.myvariable }}
# myvariable: 5